<?php
/**
 * Template Name: مجله شلنگ‌بین
 *
 * @package ShalangBin
 */

get_header();
?>
<section class="page-intro"><div class="container"><span class="eyebrow">مجله شلنگ‌بین</span><h1>دانستن، بخشی از انتخاب است</h1><p>یادداشت‌هایی برای شناخت تجهیزات و پرسیدن سؤال‌های درست.</p></div></section><section class="section"><div class="container editorial-grid"><a class="editorial-card" href="<?php echo esc_url( shalangbin_page_url( 'guide-selection' ) ); ?>"><div class="editorial-art art-0"><svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M8 3H3v5M16 3h5v5M3 16v5h5M21 16v5h-5M7 12h10M12 7v10"/></svg><span dir="ltr">FIELD NOTES / 01</span></div><div class="editorial-body"><span class="eyebrow">راهنمای انتخاب</span><h3>قبل از انتخاب دوربین، این ۵ سؤال را بپرسید</h3><p>از قطر ورودی تا نوع کابل؛ یک چک‌لیست برای شروع انتخاب.</p><span class="text-link">ادامه مطلب <svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m14 7-5 5 5 5M9 12h12"/></svg></span></div></a><a class="editorial-card" href="<?php echo esc_url( shalangbin_page_url( 'guide-cable' ) ); ?>"><div class="editorial-art art-1"><svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 6h9v12h9M3 3v6M21 15v6M6 6v15h15"/></svg><span dir="ltr">FIELD NOTES / 02</span></div><div class="editorial-body"><span class="eyebrow">شناخت تجهیزات</span><h3>کابل بلندتر، همیشه انتخاب بهتر نیست</h3><p>چگونه طول مسیر و نوع دسترسی را به انتخاب دستگاه مرتبط کنیم؟</p><span class="text-link">ادامه مطلب <svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m14 7-5 5 5 5M9 12h12"/></svg></span></div></a><a class="editorial-card" href="<?php echo esc_url( shalangbin_page_url( 'guide-care' ) ); ?>"><div class="editorial-art art-2"><svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 6a5 5 0 0 0-6 6L3 17a3 3 0 0 0 4 4l6-6a5 5 0 0 0 6-6l-3 3-4-4 2-2z"/></svg><span dir="ltr">FIELD NOTES / 03</span></div><div class="editorial-body"><span class="eyebrow">آموزش و نگهداری</span><h3>چک‌لیست پیش و پس از بازرسی</h3><p>یک روال ساده برای آماده‌سازی و بررسی وضعیت تجهیزات.</p><span class="text-link">ادامه مطلب <svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m14 7-5 5 5 5M9 12h12"/></svg></span></div></a></div></section>
<?php
get_footer();
