<?php
/**
 * Template Name: ارتباط با ما
 *
 * @package ShalangBin
 */

get_header();
?>
<section class="page-intro"><div class="container"><span class="eyebrow">ارتباط با ما</span><h1>پیش از خرید، دقیق‌تر بررسی کنیم</h1><p>کاربرد و شرایط مسیر را توضیح دهید تا یک درخواست کامل برای بررسی فنی آماده کنید.</p></div></section><section class="section"><div class="container request-layout"><aside class="request-guide"><span class="large-icon"><svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 13v-1a9 9 0 0 1 18 0v1M3 12h4v8H3zM17 12h4v8h-4z"/></svg></span><h2>برای بررسی بهتر آماده شوید</h2><ol class="numbered-list"><li><b>نیاز را مشخص کنید</b><p>کاربرد، قطر ورودی و طول تقریبی مسیر را مشخص کنید.</p></li><li><b>جزئیات را اضافه کنید</b><p>شرایط محیط و محدودیت‌های مهم را توضیح دهید.</p></li><li><b>متن را دریافت کنید</b><p>درخواست آماده‌شده را برای استفاده بعدی کپی کنید.</p></li></ol><div class="inline-notice">راه ارتباطی تأییدشده فروشگاه هنوز به این پیش‌نمایش اضافه نشده است. این فرم پیام ارسال نمی‌کند.</div></aside><form class="request-form" data-request="contact"><h2>اطلاعات درخواست</h2><p>متن درخواست را آماده و کپی کنید. در این نسخه هیچ اطلاعاتی برای فروشگاه ارسال نمی‌شود.</p><div class="form-row"><div class="field"><label for="request-name">نام شما</label><input id="request-name" name="name" required maxlength="80" autocomplete="name"></div><div class="field"><label for="request-phone">شماره موبایل</label><input id="request-phone" name="phone" required type="tel" inputmode="tel" dir="ltr" autocomplete="tel" placeholder="۰۹۱۲۱۲۳۴۵۶۷" aria-describedby="phone-hint"><small id="phone-hint">ارقام فارسی و انگلیسی پذیرفته می‌شوند.</small></div></div><div class="field"><label for="request-topic">موضوع</label><select id="request-topic" name="topic"><option value="consult">مشاوره انتخاب دستگاه</option><option value="video">درخواست نمونه تصویر</option><option value="product">بررسی مشخصات محصول</option></select></div><div class="field"><label for="request-details">توضیح کاربرد و نیاز شما</label><textarea id="request-details" name="details" rows="4" required maxlength="2000"></textarea></div><button class="btn btn-primary" type="submit">آماده‌سازی متن درخواست <svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m14 7-5 5 5 5M9 12h12"/></svg></button><p class="form-status" role="status"></p><div class="request-output" hidden><label for="request-text">متن آماده‌شده — ارسال نشده</label><textarea id="request-text" rows="8" readonly></textarea><button type="button" class="btn btn-outline" data-copy-request>کپی متن درخواست</button></div></form></div></section>
<?php
get_footer();
