<?php
/**
 * Template Name: اجاره دستگاه
 *
 * @package ShalangBin
 */

get_header();
?>
<section class="page-intro"><div class="container"><span class="eyebrow">اجاره دستگاه</span><h1>یک پروژه دارید؟ از اجاره شروع کنید.</h1><p>اطلاعات مسیر، زمان و محل پروژه را برای بررسی امکان اجاره جمع‌آوری کنید.</p></div></section><section class="section"><div class="container request-layout"><aside class="request-guide"><span class="large-icon"><svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0"/></svg></span><h2>برای بررسی بهتر آماده شوید</h2><ol class="numbered-list"><li><b>نیاز را مشخص کنید</b><p>کاربرد، قطر ورودی و طول تقریبی مسیر را مشخص کنید.</p></li><li><b>جزئیات را اضافه کنید</b><p>زمان، مدت و شهر محل اجرای پروژه را وارد کنید.</p></li><li><b>متن را دریافت کنید</b><p>درخواست آماده‌شده را برای استفاده بعدی کپی کنید.</p></li></ol><div class="inline-notice">راه ارتباطی تأییدشده فروشگاه هنوز به این پیش‌نمایش اضافه نشده است. این فرم پیام ارسال نمی‌کند.</div></aside><form class="request-form" data-request="rent"><h2>اطلاعات پروژه</h2><p>متن درخواست را آماده و کپی کنید. در این نسخه هیچ اطلاعاتی برای فروشگاه ارسال نمی‌شود.</p><div class="form-row"><div class="field"><label for="request-name">نام شما</label><input id="request-name" name="name" required maxlength="80" autocomplete="name"></div><div class="field"><label for="request-phone">شماره موبایل</label><input id="request-phone" name="phone" required type="tel" inputmode="tel" dir="ltr" autocomplete="tel" placeholder="۰۹۱۲۱۲۳۴۵۶۷" aria-describedby="phone-hint"><small id="phone-hint">ارقام فارسی و انگلیسی پذیرفته می‌شوند.</small></div></div><div class="form-row"><div class="field"><label for="request-date">تاریخ شروع پروژه</label><input id="request-date" name="date" type="date" required></div><div class="field"><label for="request-days">تعداد روز</label><input id="request-days" name="days" type="number" min="1" max="365" value="1" required></div></div><div class="field"><label for="request-city">شهر محل پروژه</label><input id="request-city" name="city" required maxlength="80" autocomplete="address-level2"></div><div class="field"><label for="request-details">توضیح کاربرد و نیاز شما</label><textarea id="request-details" name="details" rows="4" required maxlength="2000"></textarea></div><button class="btn btn-primary" type="submit">آماده‌سازی متن درخواست <svg class="icon " width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m14 7-5 5 5 5M9 12h12"/></svg></button><p class="form-status" role="status"></p><div class="request-output" hidden><label for="request-text">متن آماده‌شده — ارسال نشده</label><textarea id="request-text" rows="8" readonly></textarea><button type="button" class="btn btn-outline" data-copy-request>کپی متن درخواست</button></div></form></div></section>
<?php
get_footer();
